// <auto-generated />
namespace CaptivePortal.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_custom_field_in_user_table_And_LabelNameToDisplay_in_FormControl_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_custom_field_in_user_table_And_LabelNameToDisplay_in_FormControl_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201705151145332_added_custom_field_in_user_table_And_LabelNameToDisplay_in_FormControl_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
