// <auto-generated />
namespace CaptivePortal.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeUserIdfromSitestable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeUserIdfromSitestable));
        
        string IMigrationMetadata.Id
        {
            get { return "201704170605316_remove-UserId-from-Sites-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
