// <auto-generated />
namespace CaptivePortal.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedBackGroundColorLoginWindowColorIsPasswordRequireLoginPageTitleRegistrationPageTitleInFormTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedBackGroundColorLoginWindowColorIsPasswordRequireLoginPageTitleRegistrationPageTitleInFormTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201704170645314_added-BackGroundColor-LoginWindowColor-IsPasswordRequire-LoginPageTitle-RegistrationPageTitle-In-Form-Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
