// <auto-generated />
namespace CaptivePortal.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_adminSiteAccess_teble : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_adminSiteAccess_teble));
        
        string IMigrationMetadata.Id
        {
            get { return "201706220649061_added_adminSiteAccess_teble"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
