// <auto-generated />
namespace CaptivePortal.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewChanges_With_User_UserRole_Role : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewChanges_With_User_UserRole_Role));
        
        string IMigrationMetadata.Id
        {
            get { return "201706271058116_NewChanges_With_User_UserRole_Role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
