// <auto-generated />
namespace CaptivePortal.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeIn_usertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeIn_usertable));
        
        string IMigrationMetadata.Id
        {
            get { return "201707051112241_changeIn_user-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
