// <auto-generated />
namespace CaptivePortal.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class allow_null_to_organistaion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(allow_null_to_organistaion));
        
        string IMigrationMetadata.Id
        {
            get { return "201707110617329_allow_null_to_organistaion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
