// <auto-generated />
namespace CaptivePortal.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedHtmlStringColumninFormControlTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedHtmlStringColumninFormControlTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201704241640459_added-HtmlString-Column-in-FormControl-Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
