// <auto-generated />
namespace CaptivePortal.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changes_the_Design_database : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changes_the_Design_database));
        
        string IMigrationMetadata.Id
        {
            get { return "201705241553413_Changes_the_Design_database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
