// <auto-generated />
namespace CaptivePortal.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_GroupTable_And_GroupId_FK_in_UserTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_GroupTable_And_GroupId_FK_in_UserTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201708241330232_added_GroupTable_And_GroupId_FK_in_UserTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
