// <auto-generated />
namespace CaptivePortal.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Merge_All_Migrations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Merge_All_Migrations));
        
        string IMigrationMetadata.Id
        {
            get { return "201707100244182_Merge_All_Migrations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
