// <auto-generated />
namespace CaptivePortal.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removed_defaultSiteName_from_AdminSiteAcces_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removed_defaultSiteName_from_AdminSiteAcces_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "201707051318063_removed_defaultSiteName_from_AdminSiteAcces_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
