// <auto-generated />
namespace CaptivePortal.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changes_in_Site_and_User_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changes_in_Site_and_User_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201705201438114_changes_in_Site_and_User_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
