// <auto-generated />
namespace CaptivePortal.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class rename_default_identirty_teble : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rename_default_identirty_teble));
        
        string IMigrationMetadata.Id
        {
            get { return "201706271205209_rename_default_identirty_teble"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
